// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title FRE902EvidenceVault
 * @author Legal-X Protocol
 * @notice Self-Authenticating Digital Records Vault under Federal Rules of Evidence 902(13) & 902(14).
 * Maintains tamper-evident chain of custody, hardware enclave roots, and 28 U.S.C. § 1746 custodian attestations.
 */
contract FRE902EvidenceVault {
    struct EvidencePackage {
        bytes32 sha256Checksum;
        bytes32 blake2bChecksum;
        string matterId;
        string exhibitLabel;       // e.g. "Exhibit A-1"
        string sourceMimeType;
        uint256 originalFileSizeBytes;
        uint256 deviceCaptureTimestamp;
        uint256 blockchainAnchorTimestamp;
        address custodianAddress;
        string custodianDeclarationUri; // IPFS / Arweave URI of signed 28 U.S.C. § 1746 declaration
        bool isCertifiedFRE902_13;  // Rule 902(13): Certified Records Generated by an Electronic Process or System
        bool isCertifiedFRE902_14;  // Rule 902(14): Certified Data Copied from an Electronic Device, Storage Medium, or File
        bool isRevoked;
    }

    // sha256Checksum => EvidencePackage
    mapping(bytes32 => EvidencePackage) public evidenceRegistry;

    // matterId => array of evidence sha256 hashes
    mapping(string => bytes32[]) private matterEvidenceLists;

    event EvidenceIngestedAndCertified(
        bytes32 indexed sha256Checksum,
        string indexed matterId,
        string exhibitLabel,
        address indexed custodianAddress,
        bool fre902_13,
        bool fre902_14
    );

    event EvidenceRevoked(bytes32 indexed sha256Checksum, string indexed matterId, string reason);

    function depositAndCertifyEvidence(
        bytes32 _sha256Checksum,
        bytes32 _blake2bChecksum,
        string calldata _matterId,
        string calldata _exhibitLabel,
        string calldata _mimeType,
        uint256 _fileSizeBytes,
        uint256 _deviceCaptureTimestamp,
        string calldata _declarationUri,
        bool _isRule13,
        bool _isRule14
    ) external {
        require(evidenceRegistry[_sha256Checksum].blockchainAnchorTimestamp == 0, "Evidence hash already registered");
        require(_sha256Checksum != bytes32(0), "Invalid SHA-256");
        require(_isRule13 || _isRule14, "Must satisfy at least FRE 902(13) or 902(14)");

        evidenceRegistry[_sha256Checksum] = EvidencePackage({
            sha256Checksum: _sha256Checksum,
            blake2bChecksum: _blake2bChecksum,
            matterId: _matterId,
            exhibitLabel: _exhibitLabel,
            sourceMimeType: _mimeType,
            originalFileSizeBytes: _fileSizeBytes,
            deviceCaptureTimestamp: _deviceCaptureTimestamp,
            blockchainAnchorTimestamp: block.timestamp,
            custodianAddress: msg.sender,
            custodianDeclarationUri: _declarationUri,
            isCertifiedFRE902_13: _isRule13,
            isCertifiedFRE902_14: _isRule14,
            isRevoked: false
        });

        matterEvidenceLists[_matterId].push(_sha256Checksum);

        emit EvidenceIngestedAndCertified(
            _sha256Checksum,
            _matterId,
            _exhibitLabel,
            msg.sender,
            _isRule13,
            _isRule14
        );
    }

    function verifyEvidenceIntegrity(
        bytes32 _sha256Checksum,
        bytes32 _blake2bChecksum
    ) external view returns (bool isValid, bool isCertified, address custodian, uint256 anchorTime) {
        EvidencePackage memory pkg = evidenceRegistry[_sha256Checksum];
        if (pkg.blockchainAnchorTimestamp == 0 || pkg.isRevoked) {
            return (false, false, address(0), 0);
        }
        bool hashMatch = (pkg.blake2bChecksum == _blake2bChecksum);
        return (hashMatch, (pkg.isCertifiedFRE902_13 || pkg.isCertifiedFRE902_14), pkg.custodianAddress, pkg.blockchainAnchorTimestamp);
    }

    function getEvidenceCountByMatter(string calldata _matterId) external view returns (uint256) {
        return matterEvidenceLists[_matterId].length;
    }

    function getEvidenceHashByIndex(string calldata _matterId, uint256 _index) external view returns (bytes32) {
        require(_index < matterEvidenceLists[_matterId].length, "Index out of bounds");
        return matterEvidenceLists[_matterId][_index];
    }
}
